extensions:
  jaeger_storage:
    backends:
      memory_backend:
        memory:
          max_traces: 10000
  jaeger_query:
    storage:
      traces: memory_backend

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  jaeger_storage_exporter:
    trace_storage: memory_backend

service:
  extensions: [jaeger_storage, jaeger_query]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8889
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger_storage_exporter]
