receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
  otlp/jaeger:
    endpoint: "localhost:5317" # Pointing to Jaeger's custom port from the other window
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp] # This refers to the block above
      processors: []
      exporters: [debug, zipkin, otlp/jaeger]
